Resources:
  SampleLambdaFunction:
    Properties:
      CodeUri: .
      FunctionName: sample-lambda-function
      Handler: lambda_function.lambda_handler
      Role: !GetAtt 'SampleLambdaServiceRole.Arn'
      Runtime: python3.7
    Type: AWS::Serverless::Function
  SampleLambdaServiceRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
      Path: /
      Policies:
        - PolicyDocument:
            Statement:
              - Action: lambda:*
                Effect: Allow
                Resource: '*'
            Version: '2012-10-17'
          PolicyName: sample-policy
      RoleName: sample-lambda-service-role
    Type: AWS::IAM::Role
Transform: AWS::Serverless-2016-10-31